language: node_js

node_js:
  - "0.10"

script:
  - grunt

deploy:
  - provider: npm
    email:
      secure: T/xRKPHPI1GwomNYb3nvMntS805vdzewDKNwB+lDS6WOfXQx9td5CIbkhpfAW3zVjdbsXFVSOzufesY+RtF4gq8yvW5FhV7py6gwnEyW8LybgYssUd08W/fMoiCjORRXxwqnoHEh956z3Z9De4Q9ow47m8iniAsKRR1I1DHaKs0=
    api_key:
      secure: BCdGeRjm8i9V+gbaVNIYk7+zLyeLOQDm6eCH+NYVX137gkNBoYqL/U7GGfHoWxEvrVgN8tcCM6RrS5qU+Wu/Wy/esz1PeSoFxKEIJx+p6BCzACFl1tJWqdm/JlmnuCiZdHs6TTtfKQwaJAK4H0Kfp5qJZS9QA/RxBpkfBQZW9VY=
    on:
      tags: true
    skip_cleanup: true
