name: Documentation Deployment
on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  gh-page-build:
    runs-on: ubuntu-latest
    if: github.event_name != 'release' || github.event.release.prerelease == false
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v7
      - run: uv run mkdocs build
        env:
          MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-pages-artifact@v5
        with:
          path: site
  gh-page-deploy:
    needs: gh-page-build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
