name: Documentation Deployment

on:
  - release
  - workflow_dispatch

jobs:
  grav:
    name: Deploy Grav
    runs-on: ubuntu-latest
    steps:
      - uses: juliangruber/sleep-action@v2.0.4
        with:
          time: 3m
      - uses: actions/checkout@v6
      - name: Copy to documentation server
        uses: burnett01/rsync-deployments@v8
        with:
          switches: -avzr --delete
          path: docs/
          remote_path: /var/www/select2-docs/user/
          remote_host: ${{ secrets.DOCUMENTATION_SSH_HOST }}
          remote_port: 22
          remote_user: ${{ secrets.DOCUMENTATION_SSH_USERNAME }}
          remote_key: ${{ secrets.DOCUMENTATION_SSH_KEY }}
